### ISSUE TITLE
dwm copyright notice

### ISSUE THREAD

**Issue by sunaku** [c00kiemon5ter/monsterwm#1]
The [DWM copyright notice](http://hg.suckless.org/dwm/raw-file/tip/LICENSE) is missing from this codebase, which was forked from DWM.  Please add it!

**Comment by c00kiemon5ter** [comment]
Will do this, I just want to ask this. I'll be moving all copyright/licensing information to a separate file.
As this was based first on `catwm` then on `dwm`, and catwm is GPL'd, is it enough to just state something like:

> **LECENSE**
> This program is free software: you can redistribute it and/or modify
> it under the terms of the GNU General Public License as published by
> ....
> 
> Portions of dwm code are included in this project. Those portions are licensed as:
> MIT/X Consortium License
> ...

I would also really like to release this under MIT/ISC license, but, I'm not sure if one can or when one can change a project's license. 

**_EDIT**_: 
asked and got this:

> mjr: authors can switch licenses for future distribution at will (though earlier released versions will probably continue to be available under the earlier terms). but to go from gpl to a non-copyleft license you do need to be the copyright holder for all of the code, or have all of the other authors' agreement

**Comment by sunaku** [comment]
> I'll be moving all copyright/licensing information to a separate
> file. As this was based first on `catwm` then on `dwm`, and catwm
> is GPL'd, is it enough to just state something like:
> 
> > This program is free software: you can redistribute it and/or
> > modify it under the terms of the GNU General Public License as
> > published by ....
> > 
> > Portions of dwm code are included in this project. Those
> > portions are licensed as: MIT/X Consortium License ...  

If the ... after "MIT/X Consortium License" refers to the entire DWM
copyright notice verbatim, then yes this is acceptable.

> I would also really like to release this under MIT/ISC license, but,
> I'm not sure if one can or when one can change a project's license.  

In this case, you would need @pyknite to agree to change his catwm
license from GPLv3 to your desired license.  Similarly, @moetunes and
@jasonwryan need to agree to change the dminimalwm license from GPLv3.

Personally, I don't know why @pyknite would ever release his changes
under the GPLv3 while also failing to reproduce the DWM copyright notice
in the first place.  It's like slapping one's ancestors in the face, twice.

**Comment by c00kiemon5ter** [comment]
> If the ... after "MIT/X Consortium License" refers to the entire DWM
> copyright notice verbatim, then yes this is acceptable.

yep, that's what I meant

I think @richo4 would have to agree too. 

Thanks

**Comment by sunaku** [comment]
You're right, I missed @richo4.

**Comment by jasonwryan** [comment]
For the record, your Honour, I have no claim in the copyright of dminimalwm :)

**Comment by ghost** [comment]
I don't think i'm missed as an author. i just forked it from moetunes and as far as i know, none of my changes found its way back. anyhow: i agree.

**Comment by c00kiemon5ter** [comment]
Thanks @richo4 , I do have included your patch for "FOLLOW_MOUSE", so you should have your word on this too :)

**Comment by pyknite** [comment]
Hi there...

Sorry, I don't really use/edit/whatever catwm. So I don't really care about the licence.
Tell me what licence I should use to make everyone happy ;) 

++

**Comment by sunaku** [comment]
The easiest thing would be to retain the MIT license after you reproduce DWM's copyright notice in catwm.

**Comment by c00kiemon5ter** [comment]
@moetunes what do you say about this ?

**Comment by moetunes** [comment]
On 12/31/2011 04:38 AM, Ivan Kanakarakis wrote:

> @moetunes what do you say about this ?
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/c00kiemon5ter/monsterwm/issues/1#issuecomment-3315817

I told sunaku that catwm having a dozen lines of code shared with dwm 
does not make it a fork. I think he/she should have looked at the code 
before saying anything. I haven't looked at the code for monsterwm but I 
had the impression you were "dwm'ing" dminiwm because you like things 
that way so the claim that monsterwm is a fork might be correct.
The whole thing has come across as someone jumping the gun without 
checking anything.

**Comment by sunaku** [comment]
But those dozen lines of shared code were not produced independently (in a clean-room environment, so to speak), right?  Since catwm was written using DWM source code as reference, you _must_ adhere to the MIT license that governs the DWM source code and reproduce the copyright notice & statement in catwm.

**Comment by c00kiemon5ter** [comment]
@moetunes I'm sorry if you feel that way, I don't think that's what @sunaku wanted. 
Please, don't take this in a bad way. Lets not make this a license war :/ 

---

I do consider monsterwm as more of a dminiwm fork, but the dwm license states that: 

> The above copyright notice and this permission notice shall be included in all copies **or substantial portions** of the Software.

so, I guess, @sunaku is right, that the dwm license should be included. I have no problem with including that, I would just like to release monsterwm under MIT license too.
By your reply @moetunes , I guess you do not agree to this change (?) Please, correct me if I'm wrong.
I will include the dwm license for now, and if you agree, I'll switch. Please answer, so I can close this.

**Comment by c00kiemon5ter** [comment]
Thanks @moetunes :) 
@pyknite changing the license to [MIT/X](http://en.wikipedia.org/wiki/MIT_License) would be nice (btw, what wm do you use nowdays ?) 

I will wait for @pyknite to change the license and close this
thanks again everyone.

**Comment by sunaku** [comment]
Very well @moetunes, I won't insist on labeling dminiwm as a "DWM fork".  Nevertheless, you do need to reproduce the DWM copyright notice in dminiwm; the same applies to catwm in @pyknite's case.  That's all.
And you _don't_ need to change the catwm license; as you observed, that is something only @pyknite can do.

**Comment by sunaku** [comment]
Sounds good @c00kiemon5ter.  To summarize:
- Everyone here needs to reproduce the DWM copyright notice in their DWM-derived codebases.
- If @pyknite chooses to change the license for catwm from GPLv3 to MIT, and if everyone else downstream follows suit, then @c00kiemon5ter can finally change his monsterwm license from GPLv3 to MIT.

**Comment by pyknite** [comment]
Hi...

If it's ok for you I just change my licence to MIT and added the dwm licence to the repo...

Tell me if it's fine for you guys...

++

**Comment by c00kiemon5ter** [comment]
This is great @pyknite , thanks :)

**Comment by sunaku** [comment]
Awesome, thanks everyone!
