### ISSUE TITLE
Resizing can crash monsterwm

### ISSUE THREAD

**Issue by mil** [c00kiemon5ter/monsterwm#10]
If you resize in tiling mode there is no catch to see if you are setting W/H of XMoveResizeWindow() to 0. Thus it is possible to crash monsterwm while resizing. To see this happen: Start monsterwm, launch two windows. Hold down Alt+l. When a window is calculated as 0 width, monsterwm will crash.

See my fix here:
https://github.com/mil/monsterwm/commit/5e104b4eb299f569bea4034eebd3cf58d4efdfee

**Comment by c00kiemon5ter** [comment]
the check is against `MINWMSZ` (aka minimum window size).
there was a wrong logic operator there. 
thanks for catching and reporting this ;) 

closed by fixed commit 534c8e5d8d1d654ae52a0b1f10a24baec7c18739

**Comment by c00kiemon5ter** [comment]
btw, this can happen with stack resize too.
there is no checking there, but making windows so small 
doesn't make much sense or make them any useable.

I should probably add size checks there too. 
I've commented on this on the arch forums, and iirc on that commit (which, tbh, might have been rebased)

keep in mind that some apps (ie gvim) need a minimum size that is far greater than 1px.
