### ISSUE TITLE
selected window highlight border

### ISSUE THREAD

**Issue by Fiyorin** [c00kiemon5ter/monsterwm#14]
hi,

have you ever noticed, how when switching between windows (mod+k, mod+j), sometimes the border doesn't move to the highlighted window?
i'll see if i can reproduce it.

cheers and thanks for the awesome monsterwm!

**Comment by c00kiemon5ter** [comment]
mmm, no, it has never happened or been reported before
if you can reproduce it and describe the steps to do so,
then I will fix it asap.

**Comment by c00kiemon5ter** [comment]
note that some windows like `mplayer` do not draw the border at once 
(so it looks like no window is focused/active).
I have yet to understand why that happens, but I'm 99% sure it's not the wm's fault.
