### ISSUE TITLE
Rox-filer: dialog windows

### ISSUE THREAD

**Issue by ozar** [c00kiemon5ter/monsterwm#17]
When using rox-filer under monsterwm the main directory windows do tile as expected, but a lot of the related dialog windows tile as well when it seems that they should be floating windows instead.  When using rox-filer in other tiling WMs such as Awesome and DWM, these same dialog windows do float rather than tile by default.

Is there a shortcut to set all those dialog windows to float, or does a separate rule need to be created for each dialog window that is misbehaving?

**Comment by c00kiemon5ter** [comment]
hi, (and sorry for the delay)

looking at Rox seems to only define `_NET_WM_WINDOW_TYPE_DIALOG` 
monsterwm disregards most of EWMH so it does not check for that (while dwm and awesomewm do).

it seems though, that most of the windows take the class `Savebox` (copy, link, rename, etc)
so you may want to set a rule for that class to spawn the window in floating mode

```
{ "Savebox", -1, False, True },  /* all windows with 'Savebox' class will be floating on current desktop */
```

**Comment by ozar** [comment]
Thanks, cookie!

I had already made a rule for that category and it's working, but there are other windows still tiling that seem like they should float, so I was hoping there might be some other generic rule that would set more of them to float.  I don't want to make too many custom rules so will use it 'as is'.  Thanks again for your help...
