### ISSUE TITLE
Window Decorations ( Titlebar with minimize , maximize ,close buttons )

### ISSUE THREAD

**Issue by AmmarkoV** [c00kiemon5ter/monsterwm#18]
It would be really nice if a titlebar with the standard minimize , maximize , close buttons was availiable ( on configuration ) 

It is not so difficult to implement , wouldn't complicate the code or reduce performance and after all last time I checked its 2013  ..

**Comment by c00kiemon5ter** [comment]
:dancers: :walking: :palm_tree: :racehorse: :ghost: :cactus: 

here, copy paste one of the following themes, to the window you'd like to have that 'addon' 

:arrow_down: :arrow_upper_right: :x: 

:heavy_minus_sign: :heavy_plus_sign: :heavy_multiplication_x: 

kthnxbye!
