### ISSUE TITLE
MonsterWM output directed to console

### ISSUE THREAD

**Issue by ozar** [c00kiemon5ter/monsterwm#19]
Good day, cookie - each time I log out of monsterwm, the console is heavily saturated with various output from monsterwm, most of it being desktop and windows count output.  Otherwise, monster is just the way I want it to.

Is there any simple way to disable that output to the console itself, but still make use of it within monsterwm?  I'm currently using the windowtitles branch with the monsterwm2dzen_titles script.

Thanks for your help.

**Comment by c00kiemon5ter** [comment]
sure, you'll just need to change the last line to _not_ call `tee`

``` shell
while true; do "$wm" || break; done | tee -a "$ff"  # from this
while true; do "$wm" || break; done >"$ff"          # to this
```
