### ISSUE TITLE
Can't build on freebsd

### ISSUE THREAD

**Issue by r004** [c00kiemon5ter/monsterwm#31]
I am on FreeBSD 10 x64 and by gmake I get

```
monsterwm build options:
CFLAGS   = -std=c99 -pedantic -Wall -Wextra -I. -I/usr/include -I/usr/X11R6/include -DVERSION="cookies-git" -Os
LDFLAGS  = -L/usr/lib -lc -L/usr/X11R6/lib -lX11 -s
CC       = cc
creating config.h from config.def.h
CC monsterwm.c
monsterwm.c:11:10: fatal error: 'X11/Xutil.h' file not found
#include <X11/Xutil.h>
         ^
1 error generated.
gmake: *** [monsterwm.o] Error 
```

So I added `-I/usr/local/include` at the end of CFALGS line and I got 

```
cc: warning: argument unused during compilation: '-L/usr/local/include'
monsterwm.c:11:10: fatal error: 'X11/Xutil.h' file not found
#include <X11/Xutil.h>
         ^
1 error generated.
gmake: *** [monsterwm.o] Error 
```

**Comment by c00kiemon5ter** [comment]
there have been people that built monsterwm on DragonFly and Free BSD. 
See the posts [here](https://bbs.archlinux.org/viewtopic.php?pid=1048662#p1048662) and [here](https://bbs.archlinux.org/viewtopic.php?pid=1049493#p1049493). 
as noted, `pkgconfig` can help you locate the correct paths.

**Comment by r004** [comment]
```
X11INC = -I/usr/local/include/X11
X11LIB = -L/usr/local/lib -lX11

INCS = -I. -I/usr/local/include ${X11INC}
LIBS = -L/usr/local/lib -lc ${X11LIB}
```

it is not quite what you post for freebsd 9 but I get this:

``` gmake
monsterwm build options:
CFLAGS   = -std=c99 -pedantic -Wall -Wextra -I. -I/usr/local/include -I/usr/local/include/X11 -DVERSION="cookies-git" -Os
LDFLAGS  = -L/usr/local/lib -lc -L/usr/local/lib -lX11 -s
CC       = cc
CC monsterwm.c
In file included from monsterwm.c:11:
In file included from /usr/local/include/X11/Xutil.h:53:
In file included from /usr/local/include/X11/Xlib.h:47:
/usr/local/include/X11/Xfuncproto.h:145:24: warning: named variadic macros are a
      GNU extension [-Wvariadic-macros]
#define _X_NONNULL(args...)  __attribute__((nonnull(args)))
                       ^
1 warning generated.
CC -o monsterwm
```

Is it building properly? or should I do excatly as you posted?

**Comment by c00kiemon5ter** [comment]
The build should be fine. 
The warnings is generated by `Xfuncproto.h` line 145, where it uses _named variadic macros_. 
C99 provides a way to use n.v.m. properly through `__VA_ARGS__` [[ref](http://c0x.coding-guidelines.com/6.10.3.html)]. 

The warning may go away by using `-std=gnuc` instead of `-std=c99` in `CFLAGS`.

**Comment by r004** [comment]
error: invalid value 'gnuc' in '-std=gnuc'

I thing it is because FreeBSD used Clang/llvm from version 10.
any work around?

**Comment by c00kiemon5ter** [comment]
right, sorry, that should be `gnu99` [[ref](https://gcc.gnu.org/onlinedocs/gcc-4.1.2/gcc/Standards.html)]

**Comment by c00kiemon5ter** [comment]
for clang the same applies [[ref](http://clang.llvm.org/docs/UsersManual.html)]

> clang supports the -std option, which changes what language mode clang uses. The supported modes for C are c89, gnu89, c94, c99, gnu99 and various aliases for those modes. If no -std option is specified, clang defaults to gnu99 mode.
