### ISSUE TITLE
How do you apply patches 2 monsterwm

### ISSUE THREAD

**Issue by GithubAccount453** [c00kiemon5ter/monsterwm#34]

**Comment by c00kiemon5ter** [comment]
Hello, from the readme:

> Some extensions to the code are supported in the form of patches. See other branches for the patch and code. Easiest way to apply a patch, is to `git merge` that branch.

You can also `rebase` a feature branch upon another.

**Comment by GithubAccount453** [comment]
It doesn't allow me to use more than 1 branch with git merge. The command I am using is git merge origin/uselessgaps but I also want too use other branches like centerwindow

**Comment by c00kiemon5ter** [comment]
The following should just work

```
git clone git@github.com:c00kiemon5ter/monsterwm.git
cd monsterwm/
git merge origin/uselessgaps
git merge origin/centerwindow
```
