### ISSUE TITLE
Not detecting screen resolution

### ISSUE THREAD

**Issue by StephenLangHall** [c00kiemon5ter/monsterwm#37]
I'm using xrandr to set the screen size (800x600), and when I start monsterwm afterwards, it does not fit the size.  It still goes outside the edges of the screen.

.xinitrc:  
```
xrandr --output Virtual-1 --mode 800x600 &
xwallpaper --zoom /root/Files/Images/stream.jpg &
monsterwm
```

**Comment by c00kiemon5ter** [comment]
hey there, I have not worked on this project for a long time and afaik there are forks continuing this or derivative or similar work.

Having said this, you may want to chain the commands to make sure that all is in sync

```
xrandr --output Virtual-1 --mode 800x600 \
  && xwallpaper --zoom /root/Files/Images/stream.jpg \
  && monsterwm
```

**Comment by StephenLangHall** [comment]
Ok. Thanks!
