### ISSUE TITLE
Follow Desktop puts window under existing windows

### ISSUE THREAD

**Issue by firecat53** [c00kiemon5ter/monsterwm#7]
When certain programs (for example mplayer) are set in config.h to follow to a new desktop on launch, they get placed underneath any existing windows on that desktop. For example, I have mplayer set like:
{ "MPlayer",     3,    True,   False  }, and when it is launched from urxtv in desktop 0, the desktop changes to 3, but mplayer is placed underneath an existing urxvt window there. Same thing happens with dwb and Firefox. 

The send-to-desktop command seems to work correctly, however.

Thanks!
Scott

(commit #b6f2f0076e3f) on master branch w/ useless gaps

**Comment by c00kiemon5ter** [comment]
> they get placed underneath any existing windows on that desktop

by that you mean that they do not get focus and become the current window, I guess. 
underneath, as in their borders are under the other windows' borders. right ? 

this is easy to fix. will push in a min.

**Comment by c00kiemon5ter** [comment]
closed by 5b11f8e52a8e8ba09290123a1c7f6289e2255b24

**Comment by firecat53** [comment]
Perfect! Thanks :)
